language: node_js
node_js:
  - "7"
  - "6"
env:
  NODE_ENV: development
  NODE_ENV: production
install:
  - git clone --depth=1 https://github.com/doodadjs/travis_scripts.git travis_scripts
  - ./travis_scripts/install.sh
  - cd node_modules/doodad-js-test