dist: trusty
language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
cache:
  directories:
    - $HOME/build/clean
env:
  - NODE_ENV=development
  - NODE_ENV=production
before_install: git clone --depth=1 https://github.com/doodadjs/travis_scripts.git ~/travis_scripts && chmod +x ~/travis_scripts/install.sh
install: TARGET=$HOME/build/clean; export DD_REPOS=`cd $TRAVIS_BUILD_DIR/.. && pwd`; mkdir -p $TARGET && cd $TARGET && ~/travis_scripts/install.sh && cd doodad-js-test
