language: node_js
node_js:
  - "8"
  - "7"
  - "6"
env:
  - NODE_ENV=development
  - NODE_ENV=production
before_install: mkdir -p ~/build/clean && cd ~/build/clean && git clone --depth=1 https://github.com/doodadjs/travis_scripts.git travis_scripts && chmod +x ./travis_scripts/install.sh
install: cd ~/build/clean && ./travis_scripts/install.sh && cd doodad-js-test