language: node_js
node_js:
  - "8"
  - "7"
  - "6"
env:
  - NODE_ENV=development
  - NODE_ENV=production
before_install: git clone --depth=1 https://github.com/doodadjs/travis_scripts.git ~/travis_scripts && chmod +x ~/travis_scripts/install.sh
install: TARGET=~/build/clean; DD_REPOS=`cd .. && pwd`; mkdir -p $TARGET && cd $TARGET && ~/travis_scripts/install.sh && cd doodad-js-test
