language: node_js
node_js:
  - "8"
  - "7"
  - "6"
env:
  - NODE_ENV=development
  - NODE_ENV=production
before_install: cd .. && git clone --depth=1 https://github.com/doodadjs/travis_scripts.git travis_scripts && chmod +x ./travis_scripts/install.sh
install: ./travis_scripts/install.sh && cd node_modules/doodad-js-test